### ISSUE TITLE
Mobile - filters select

### ISSUE THREAD

**Issue by zlaasu** [Glennmen/PMSF#16]
It's real hard for mobile people to change filters (ex. chrome users). 

It will be much better to change it to something different. Maybe the checkbox list? It will be great.

This is the main issues from my map users. Everyone has a problem with that. 

//zlasu

**Comment by baskettcase** [comment]
I agree. It's really really bad in iOS safari also

**Comment by Glennmen** [comment]
This is planned together/after the frontend redesign (no timeframe for now, but I hope soon).

**Comment by Glennmen** [comment]
There will be a more mobile friendly filter system in the new frontend, I am closing this issue.
If you have any questions you can reopen it or ask in the PMSF Discord server.
