### ISSUE TITLE
[Idea] Gym Name and Picture

### ISSUE THREAD

**Issue by LabSen** [Glennmen/PMSF#17]
I run Monocle with this PR: https://github.com/Noctem/Monocle/pull/350

Is it possible to take the Gym Name and Picture on the Gym Detail?

**Comment by Glennmen** [comment]
This might be possible in the near future after James his backend rewrite.
It will make adding new platforms/forks easier.

**Comment by LabSen** [comment]
Did some Scanner-Config (RM or so) GYM Name or Picture currently support? Then can i try to add the Monocle PR

**Comment by Glennmen** [comment]
This will be included in the new frontend, I will close this issue for now.
If you have any questions you can reopen it or ask in the PMSF Discord server.
