### ISSUE TITLE
Missing Monocle features

### ISSUE THREAD

**Issue by MrCanan** [Glennmen/PMSF#18]
Hi,

First, thanks for your awesome work. =)

But saddly, even if there is all features from RocketMap, features from Monocle are missing, like "Trash" to split Pokemons on map, "Area" to see zone limit (especially geofence), etc.

Is it planned to add them (or other) ?

Very cordially.

**Comment by Glennmen** [comment]
Is "Trash" needed on the frontend? What use does it have for users?
"Area" has been suggested before and will be added once I have time.

**Comment by MrCanan** [comment]
Hi back,

The "Trash" option of Monocle is useful to split in two parts all Pokemons on map.
So for exemple, I can display only rare and ultra rare Pokemons on map, and put all other in "Trash" to allow low player to fill their Pokedex without polluate the map.

I am happy to know you wil ladd the "Area" option when you will have time. =)

Very cordially.

**Comment by Glennmen** [comment]
I don't see any use of the "Trash" option, people can filter pokemon on their map how they want.
Area is on the list.

Will close this issue.
