### ISSUE TITLE
Support for a new fork, by Monkey

### ISSUE THREAD

**Issue by ARGG1** [Glennmen/PMSF#19]
Hello,

Monkey has been churning out nice PRs for Monocle. He created a fork that does CP/Level/Raids/UnownForm/GymDetails!! << GYM DETAILS!

Could you kindly support this fork? https://github.com/MonkeyTedBaker/Monocle/commits/develop

Thanks.

**Comment by Glennmen** [comment]
This might be possible in the near future after James his backend rewrite.
It will make adding new platforms/forks easier.

**Comment by cptmedic** [comment]
PR #28 covers this nicely.

**Comment by Glennmen** [comment]
PR #28 (Monkey support) has been merged so this issue will be closed.
