### ISSUE TITLE
Chrome Mobile Push-Notifications not working

### ISSUE THREAD

**Issue by Falaris01** [Glennmen/PMSF#20]
PMSF is working well with Chrome for Android but push notifications are not working - you hear the sound of an Alarm but a push notification is not showing. It used to work with Samsungs own browser but since it has been updated that doesn't work anymore either.

Currently you have to use Firefox to recieve push notification through your browser on Android. 

For RocketMap it is being worked on in PR#2138

**Comment by Glennmen** [comment]
Will need to try to recreate it.
Anyone else with this same issue?

**Comment by zlaasu** [comment]
I confirm this. The sound works but no notification. Ofcorse we are talking about local notification not push.

**Comment by wateredstorm** [comment]
I can confirm this aswell.

**Comment by CalamityJames** [comment]
@Falaris01 @zlaasu @wateredstorm Can you confirm if you are using SSL or not for your maps?

**Comment by Falaris01** [comment]
I'm using SSL for my map.

**Comment by Glennmen** [comment]
Notification fix is being worked on in PR #88 but we need testers.

**Comment by wateredstorm** [comment]
Been a while!
Glad to see its going there hehe, let me know if testing needs to be done.

**Comment by Glennmen** [comment]
Notification fix PR #88 has been merged, will close this issue.
