### ISSUE TITLE
Gyms and Raids

### ISSUE THREAD

**Issue by baskettcase** [Glennmen/PMSF#3]
What kind of database structure are you looking for with displaying gyms and raids with monocle?

**Comment by Glennmen** [comment]
There is an issue currently, I am working on a fix.
PMSF will be updated for Chrales his raid fork.
https://github.com/ZeChrales/Monocle/tree/raids

**Comment by baskettcase** [comment]
I have his PR installed but not his fork. Plus no gyms are showing up so does gyms work for you? My forts table has no mods, so is a default install from Monocle and yet nothing is showing up. 

Update: ah you said working on a fix, it sounded like you were talking about raids, but Im realizing you might be talking about gyms. Thanks!

**Comment by Glennmen** [comment]
@baskettcase Chrales hasn't pushed a PR yet, so only his fork is available. If you are not running on his fork then gyms won't work.
You should also join my discord server for more info/help ;)
