### ISSUE TITLE
[idea] Switch to enable global iv notification (for notification of excluded pokes)

### ISSUE THREAD

**Issue by M4d40** [Glennmen/PMSF#39]
Would it be possible to make a switch to include excluded pokemon in the notification, if they are over iv filter?

**A little switch like "Include excluded pokemon" or sth.**
(In the notification settings, under the iv setting)

Case:
Exclude pokes that normally don't interest you, but high IVs are still important and many want to get still notifies for example if a poke over 95% appear even if they are normally not interesting.
(especially if it is a 100%)

**Comment by Glennmen** [comment]
This would need a rewrite of current behaviour, right now pokemon filtering happens on server side.

**Comment by Ricola3D** [comment]
So the function "processPokemons" in map.js is executed server-side ? I am asking because I'm looking if it is possible to add a feature "exclude IVs inferior to" in the code for my map.

**Comment by Glennmen** [comment]
@Ricola3D map.js (javascript code) is executed client-side.
There is server-side and client-side pokemon filtering.

**Comment by hammydown4325** [comment]
Checkout this PR https://github.com/Glennmen/PMSF/pull/54
