### ISSUE TITLE
Adjust RAID marker settings doesn't update off viewable area

### ISSUE THREAD

**Issue by peterchabs** [Glennmen/PMSF#8]
If you change RAID Marker settings from lets say 2 to 4, gyms not currently viewable on the map aren't updated correctly.
Using RM DB structure.
![image](https://user-images.githubusercontent.com/26359726/28239037-a9768356-6927-11e7-9380-b5cccaaca517.png)

**Comment by ultrafunkamsterdam** [comment]
Yeah also the last_gyms last_pokemons are not working like in RM. You get returned all pokemon and gyms every 5 seconds even if you hold your map still. Maybe something to sort out for the future, or is it on purpose?

**Comment by ultrafunkamsterdam** [comment]
^^ i got a fix for that already. its in the def of newarea.

**Comment by Glennmen** [comment]
@ultrafunkamsterdam If you have Monocle DB scheme it is not possible to make it work like RM because Monocle doesn't keep last_scanned time.

And instead of saying that you have a fix how about sharing it?

**Comment by Glennmen** [comment]
Heard nothing about this issue anymore so will be closing it.
Please reopen if this issue still exists.
